### ISSUE TITLE
Error "renaming" sessions on W10

### ISSUE THREAD

**Issue by KazuoCode** [gthubdev/website#20]
Theres an error that appeared with #19 on Windows (at least W10). Theres no problem with the code on the PR but the sessions keep throwing errors.

**Comment by delta-one** [comment]
I think this can be solved by changing how the sessions are stored on the server. Right now we are using a file-based session store, but there might be better alternatives out there. Since this is low priority, we can take a closer look at it during the summer maybe.

**Comment by KazuoCode** [comment]
Seems worthy taking a look at later on.

**Comment by delta-one** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error "renaming" sessions on W10](https://trello.com/c/j7bZK2Nd/27-error-renaming-sessions-on-w10)
